### ISSUE TITLE
How can I built a PCB for this program

### ISSUE THREAD

**Issue by Mime-AL** [nzc21489/pico_usb-i2s#1]
I see a [Si5351](https://github.com/nzc21489/pico_usb-i2s/tree/main/pico_usb_i2s/Si5351) lib on the project，But I don't understan how to connect them.
Should I use pico‘s MCLK out as Si5351’s reference clock，and SI5351 CLK output connect to DAC chip？
Also is it support 24bit sampling depth？

**Comment by nzc21489** [comment]
Si5351 and EZ-USB FX2 LP is needed except Raspberry Pi Pico.
For EZ-USB FX2 LP program, you should see fx2_usb-i2s (https://github.com/nzc21489/fx2_usb-i2s).

Pin out is
EZ-USB ←→ Pico
PB0〜PB7 → GPIO2〜GPIO9
CTL1 → GPIO10
CTL0 → GPIO11
PA0 → GPIO12
PA1 → GPIO13
PA2 ← GPIO14

Pico ←→ Si5351
GPIO27 → I2C SCL
GPIO26 ←→ I2C SDA
GPIO20  ← CLK0(I2S MCLK)
GPIO21  ← CLK2(I2S LRCK)
(No connection)   CLK1(I2S BCK)
GPIO22(I2S DATA)   (No connection)

For reference clock for Si5351, you should connect 25MHz crystal.

Supported format is
16/24/32bit, 44.1/48/88.2/96/176.4/192/352.8/384kHz

**Comment by Mime-AL** [comment]
Thanks a lot, I will have a try.
